blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/RhythmPahwa14/Code-Editor/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Contributing Guidelines
    url: https://github.com/RhythmPahwa14/Code-Editor/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to this project